server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Público: AUTH
        - id: autenticacao
          uri: ${AUTH_SERVICE_URI:http://host.docker.internal:8086}
          predicates:
            - Path=/auth/**

        # Protegidos (passam no filtro TokenValidation)
        - id: usuarios
          uri: ${USER_SERVICE_URI:http://host.docker.internal:8082}
          predicates:
            - Path=/usuarios/**
          filters:
            - TokenValidation

        - id: eventos
          uri: ${EVENT_SERVICE_URI:http://host.docker.internal:8083}
          predicates:
            - Path=/eventos/**
          filters:
            - TokenValidation

        - id: ingressos
          uri: ${INGRESSOS_SERVICE_URI:http://host.docker.internal:8081}
          predicates:
            - Path=/tickets/**
          filters:
            - TokenValidation

        - id: avaliacoes
          uri: ${AVALIACAO_SERVICE_URI:http://host.docker.internal:8084}
          predicates:
            - Path=/avaliacoes/**
          filters:
            - TokenValidation

        - id: notifications
          uri: ${NOTIFICATIONS_SERVICE_URI:http://host.docker.internal:8085}
          predicates:
            - Path=/notifications/**
          filters:
            - TokenValidation

app:
  auth:
    validate-url: ${AUTH_VALIDATE_URL:http://host.docker.internal:8086/auth/validate}
    timeout-ms: 2500
