# src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ingressos-service
          uri: http://localhost:8081
          predicates:
            - Path=/tickets,/tickets/**
  # (opcional) CORS liberado para teste rápido
  webflux:
    base-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info

