server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # Ingressos
        - id: ingressos
          uri: http://ingressos-service:8081
          predicates:
            - Path=/tickets/**

        # Eventos
        - id: eventos
          uri: http://event-service:8083
          predicates:
            - Path=/eventos/**

        # Avalicações
        - id: avaliacoes
          uri: http://avaliacao-service:8084
          predicates:
            - Path=/avaliacoes/**

        # Notificações
        - id: notifications
          uri: http://notifications-service:8085
          predicates:
            - Path=/notifications/**
            -
